Add erb formatter support
lassik/emacs-format-all-the-code pull request #193
Opened 2022-06-25 17:40 UTC by nbelzer

Couldn't find any guidelines to contributing so my apologies if something is not handled properly.

- Added matcher to match files ending in `.erb` to the `_Erb` language (which was unsupported before).
- Adds support for [erb-formatter](https://github.com/nebulab/erb-formatter) to format `_Erb` files.

2022-06-25 17:41 UTC, nbelzer commented on format-all.el
> +      (and (string-match-p ".erb\\'" buffer-file-name) "_Erb")
Would love to hear suggestions on how to handle this in a better way

2022-06-27 19:14 UTC, nbelzer commented
> We could add all of these to [language-id](https://github.com/lassik/emacs-language-id). It seems possible to tell them apart by filename extension. What Emacs modes do people use to edit ERB? I can't find an erb-mode. Does web-mode support it?

ERB is indeed supported by web-mode (which is also the major mode I am using when editing `.html.erb` files). As far as I am aware, `erb-formatter` only handles HTML files. Because of this I would suggest we only add support for `HTML+ERB`.  I'll update the matcher to be more selective based on the filename (`.html.erb` instead of just `.erb`) and update the language-id.

2022-06-27 19:27 UTC, nbelzer commented
I've left two fixups (to make it clear what I've changed).  If you are okay with these changes I can rebase the PR to clean them up before we merge.

2022-06-27 21:28 UTC, lassik commented
Format-all uses a separate library called language-id.el to determine what language is used in the buffer to be formatted. Only languages for which there isn't an official GitHub Linguist ID are special-cased in format-all.el as a necessary hack.

Since both HTML+ERB and JavaScript+ERB are official LInguist IDs, I added them directly to language-id.el and we don't have to add any special-case code to detect them in format-all itself.

Hence, the PR looks fine as it is, but can you remove the special-case `(and (string-match-p ".erb\\'" buffer-file-name) "HTML+ERB")`?

2022-06-27 22:20 UTC, nbelzer commented on format-all.el
> +      (and (string-match-p ".erb\\'" buffer-file-name) "_Erb")
This no longer applies.

2022-06-28 07:04 UTC, lassik requested changes

2022-06-28 07:04 UTC, lassik commented on README.md
> +* **Erb** ([erb-formatter](https://github.com/nebulab/erb-formatter))
Please make it `[*erb-formatter*]` like the others.

2022-06-28 07:07 UTC, lassik commented
Hmm. We should probably refer to the formatter as `erb-format` since that's the name of the shell command used to run it. Seems clearer to me than `erb-formatter` which is the name of the Ruby module and gem. What do you think?

2022-06-28 07:21 UTC, nbelzer commented
Agree, also seems more in line with the other formatters.  I've made the changes

2022-06-28 07:41 UTC, lassik commented
Perfect. Thanks a lot for sticking with it!

2022-06-28 07:41 UTC, merged