Adding formatter support for HLSL and AZSL
lassik/emacs-format-all-the-code pull request #255
Opened 2024-05-09 02:42 UTC by xeechou

[HLSL](https://github.com/xeechou/hlsl-mode.el) is a popular C++ like shading language used in gaming industry. 

[AZSL](https://github.com/xeechou/azsl-mode.el) (Amazon shading language) is a HLSL dialect used in [o3de](https://github.com/o3de/o3de/).

Both languages use very similar syntax to C++. This patch add the two languages support in format-all.

I have implemented both languages major mode in emacs.

2024-05-10 13:48 UTC, lassik requested changes

2024-05-10 13:48 UTC, lassik commented on format-all.el
> +      (and (equal major-mode 'hlsl-mode) "_HLSL")
Please remove this line.

2024-05-10 13:48 UTC, lassik commented on format-all.el
> +    ("_HLSL" clang-format)
Please change `"_HLSL"` to `"HLSL"`.

2024-05-10 13:48 UTC, lassik commented on format-all.el
> +    ("_HLSL" clang-format)
And move `"HLSL"` between HCL and HTML.

2024-05-10 13:48 UTC, lassik commented on format-all.el
> +    ("_AZSL" clang-format))
Please move `_AZSL` between `_Angular` and `_Beancount`.

2024-05-10 13:48 UTC, lassik commented on format-all.el
> +      (and (equal major-mode 'azsl-mode) "_AZSL")
Please move `_AZSL` before `_Beancount`.

2024-05-10 13:51 UTC, lassik commented
Thank you.

HLSL is officially recognized by GitHub Linguist, so I [added it to the language-id library](https://github.com/lassik/emacs-language-id/commit/435114f208b97e97aa1576ef1966a33d90cad01b). No `_` needed.

Please also add `"HLSL"` and `"_AZSL"` to the `:languages` list inside `(define-format-all-formatter clang-format ...)`.

2024-05-11 17:45 UTC, xeechou commented
Hi, thanks. The MR is updated.

2024-05-11 18:11 UTC, merged

2024-05-11 18:11 UTC, lassik commented
Thank you for the good work!